image: ubuntu:20.04

stages:
  - build
  - test
  - deploy

default:
  before_script:
    - pwd
    - su -
    - apt-get update
    - apt-get --assume-yes install sudo curl
    - apt-get update
    - apt-get --assume-yes install software-properties-common wget tar
    - sudo apt-get update
    - sudo mkdir -p /usr/java/oracle
    - cd /usr/java/oracle
    - wget https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz
    - sudo tar -xzvf openjdk-16.0.1_linux-x64_bin.tar.gz
    - export JAVA_HOME=/usr/java/oracle/jdk-16.0.1
    - export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
    - cd /builds/pap_21l/z03/pap21l-z03
    - sudo mkdir -p /usr/maven
    - cd /usr/maven
    - wget https://www.dropbox.com/s/a5bmmzbwkvilkbj/apache-maven-3.8.1-bin.tar.gz?dl=1
    - sudo tar -xzvf apache-maven-3.8.1-bin.tar.gz@dl=1
    - export MAVEN_HOME=/usr/maven/apache-maven-3.8.1
    - export PATH=$PATH:$HOME/bin:$MAVEN_HOME/bin
    - cd /builds/pap_21l/z03/pap21l-z03
    - apt-get update && apt-get --assume-yes install mysql-server mysql-client libmysqlclient-dev
    - service mysql start
    - mysql -u root -e "SELECT User, Host, plugin FROM mysql.user;"
    - mysql -u root -e "CREATE USER 'springuser'@'%' IDENTIFIED BY 'ThePassword';"
    - mysql -u root -e "CREATE DATABASE chatter;"
    - mysql -u root -e "GRANT ALL ON chatter.* TO 'springuser'@'%';"
    - mysql -u root -e "SET GLOBAL time_zone = '+02:00';"
    - mysql -u root -e "FLUSH PRIVILEGES"

build-code-job1:
  stage: build
  script: mvn compile

test-code-job1:
  stage: test
  script: mvn test
  needs: [build-code-job1]

deploy-code-job1:
  stage: deploy
  script: mvn package
  only: [master]
  artifacts:
      paths: [target/*.jar]
      expire_in: 3 days
