image: maven:latest
# Zrobić ubuntu i pobrać mavena

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: db_example
  MYSQL_USER: springuser
  MYSQL_USER_PASSWORD: ThePassword
  MYSQL_ROOT_PASSWORD: root
  DB_HOST: mysql

stages:
  - preparation
  - build
  - test
  - deploy

db-seeding:
  stage: preparation
  image: mysql:latest
  services:
    - mysql
  script:
    - echo "CREATE DATABASE chatter;" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host="DB_HOST" "$MYSQL_DATABASE"
    - echo "CREATE USER 'springuser'@'%' IDENTIFIED BY 'ThePassword';" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host="DB_HOST" "$MYSQL_DATABASE"
    - echo "GRANT ALL ON chatter.* TO 'springuser'@'%';" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host="DB_HOST" "$MYSQL_DATABASE"
    - echo "FLUSH PRIVILEGES" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host="DB_HOST" "$MYSQL_DATABASE"

build-code-job1:
  stage: build
  dependencies:
    - db-seeding
  script: mvn compile

test-code-job1:
  stage: test
  script: mvn test
  needs: [build-code-job1]

deploy-code-job1:
  stage: deploy
  script: mvn package
  only: [master]
  artifacts:
      paths: [target/*.jar]
      expire_in: 3 days
